export async function handler(event, context) {
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://kumarsite.netlify.app/</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/about</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/projects</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/trends</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/learning</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/music</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/contact</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/learning/shortcuts</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/learning/vocab-additions</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/spine-implant-dashboard</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/building-mcp-server-with-cursor</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/drug-suggestion-app</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/portfolio-website</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/my-experience-with-windsurf</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/experience-using-api-in-ai-code-editor</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/acronym-soup</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/andrej-karpathy-yc-ai-startup-school</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/my-fascination-with-shortcuts</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/compelling-india-story</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/microsoft-mai-dx-india</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/acronym-soup-revisited-2025</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/price-parity</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/started-to-kindle-again</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/autophagy</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/feynman-technique</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/applying-robinson-method</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/memory-evolution</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/nepal-annapurna-circuit</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/my-random-thoughts-this-week</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/nammu-soil-analysis-research</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/india-usa-trade-gap-2025</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/top-9-famous-rules</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/the-great-pivot</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/long-weekend-musings-2025</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/faq-budding-dentist</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://kumarsite.netlify.app/blog/devastated-by-young-girls-demise</loc>
    <lastmod>2025-08-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>`;

  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600'
    },
    body: sitemap
  };
}
