steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/gen-lang-client-0261683563/react-docker-repo/react-app-production:${COMMIT_SHA}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/gen-lang-client-0261683563/react-docker-repo/react-app-production:${COMMIT_SHA}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'react-app-production'
      - '--image'
      - 'us-central1-docker.pkg.dev/gen-lang-client-0261683563/react-docker-repo/react-app-production:${COMMIT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/gen-lang-client-0261683563/react-docker-repo/react-app-production:${COMMIT_SHA}'
