[build]
  base = "."
  command = "npm ci --include=dev && npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false", NODE_VERSION = "20", NPM_FLAGS = "--include=dev" }

# Form processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Netlify functions for security and CSP headers
[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

# Add security headers via edge functions
[[edge_functions]]
  function = "csp-headers"
  path = "/*"

# Serve static files directly (PDFs, images, etc.)
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# Serve static files directly (PDFs, images, etc.)
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# SPA fallback - redirect all other requests to index.html (lowest priority)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
