[build]
  base = "."
  command = "npm run build"
  publish = "dist"

# No Netlify functions needed for analytics; GA4 is used directly
[functions]
  directory = "netlify/functions"

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
