# Single page app (SPA) fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle blog posts without extensions
[[redirects]]
  from = "/blog/:slug"
  to = "/index.html"
  status = 200
  force = false

# Handle direct access to .jsx files
[[redirects]]
  from = "/blog/*.jsx"
  to = "/index.html"
  status = 200
  force = false
