[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false", NODE_VERSION = "20" }

# Netlify functions for security and CSP headers
[functions]
  directory = "netlify/functions"

# Add security headers via edge functions
[[edge_functions]]
  function = "csp-headers"
  path = "/*"

# Serve static files directly (PDFs, images, etc.)
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# Serve static files directly (PDFs, images, etc.)
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# SPA fallback - redirect all other requests to index.html (lowest priority)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
