[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false", NODE_VERSION = "20" }

# No Netlify functions needed for analytics; GA4 is used directly
[functions]
  directory = "netlify/functions"

# Serve static files directly (PDFs, images, etc.)
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# Serve sitemap.xml directly with proper headers
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

# Serve sitemap-index.xml as alternative
[[redirects]]
  from = "/sitemap-index.xml"
  to = "/sitemap-index.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

# Serve robots.txt directly with proper headers
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
