[build]
  base = "."
  command = "npm run build"
  publish = "dist"

# SPA fallback - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Analytics function configuration
[functions]
  directory = "netlify/functions"
