name: Render PlantUML diagrams

on:
  pull_request:
    paths:
      - 'docs/*.puml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render PlantUML to SVG (Docker)
        run: |
          docker run --rm -v "${{ github.workspace }}":/workspace plantuml/plantuml -tsvg docs/reco-architecture-*.puml

      - name: Commit rendered SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): render PlantUML diagrams to SVG"
          file_pattern: docs/*.svg



